In [2]:
import numpy as np
def s(x):
    return 1 / (1 + np.exp(-x))
def sd(y):
    return y * (1 - y)
def r(x):
    return np.maximum(0, x)
def rd(x):
    return (x > 0).astype(float)
X = np.array([[1, 1, 0, 1]])
Y = np.array([[1]])
l = 0.69
t = 0.001
W = np.array([
    [ 0.3,  0.1],
    [-0.2,  0.4],
    [ 0.2, -0.3],
    [ 0.1,  0.4]
])
B = np.array([[0.2, 0.1]])
V = np.array([
    [-0.3],
    [ 0.2]
])
C = np.array([[-0.3]])
e = 0
p = False
while True:
    e += 1
    z = np.dot(X, W) + B
    h = r(z)
    u = np.dot(h, V) + C
    o = s(u)
    d = Y - o
    do = d * sd(o)
    dh = do.dot(V.T) * rd(z)
    V += l * h.T.dot(do)
    C += l * do
    W += l * X.T.dot(dh)
    B += l * dh
    if not p:
        print("\n First Epoch")
        print("Output :", o)
        print("Error :", d)
        print("After updating W1:\n", W)
        print("After updating b1:\n", B)
        print("After updating W2:\n", V)
        print("After updating b2:\n", C)
        p = True
    if abs(d[0][0]) < t:
        print("\n Last Epoch")
        print("Epoch:", e)
        print("Output :", o)
        print("Error:", d)
        print("Final W1:\n", W)
        print("Final b1:\n", B)
        print("Final W2:\n", V)
        print("Final b2:\n", C)
        break


 First Epoch
Output : [[0.44522076]]
Error : [[0.55477924]]
After updating W1:
 [[ 0.27163478  0.11891015]
 [-0.22836522  0.41891015]
 [ 0.2        -0.3       ]
 [ 0.07163478  0.41891015]]
After updating b1:
 [[0.17163478 0.11891015]]
After updating W2:
 [[-0.26217971]
 [ 0.29455073]]
After updating b2:
 [[-0.20544927]]

 Last Epoch
Epoch: 29883
Output : [[0.999]]
Error: [[0.001]]
Final W1:
 [[ 0.19432311  0.75490974]
 [-0.30567689  1.05490974]
 [ 0.2        -0.3       ]
 [-0.00567689  1.05490974]]
Final b1:
 [[0.09432311 0.75490974]]
Final W2:
 [[-0.21095167]
 [ 1.75804256]]
Final b2:
 [[0.5432982]]


In [1]:
import numpy as np
def sigmoid(x):
    return 1 / (1 + np.exp(-x))
def sigmoid_derivative(y):
    return y * (1 - y)
def relu(x):
    return np.maximum(0, x)
def relu_derivative(x):
    return (x > 0).astype(float)
def leaky_relu(x, alpha=0.01):
    return np.where(x > 0, x, alpha * x)
def leaky_relu_derivative(x, alpha=0.01):
    return np.where(x > 0, 1, alpha)
def tanh(x):
    return np.tanh(x)
def tanh_derivative(x):
    return 1 - np.tanh(x)**2
def swish(x):
    return x / (1 + np.exp(-x))
def swish_derivative(x):
    sig = 1 / (1 + np.exp(-x))
    return sig + x * sig * (1 - sig)
def softmax(x):
    exp_x = np.exp(x - np.max(x))
    return exp_x / np.sum(exp_x, axis=1, keepdims=True)
def softmax_derivative(softmax_output):
    s = softmax_output.reshape(-1, 1)
    return np.diagflat(s) - np.dot(s, s.T)
X = np.array([[1, 1, 0, 1]])
Y = np.array([[1]])   
l = 0.69
t = 0.001
W = np.array([
    [0.3, 0.1],
    [-0.2, 0.4],
    [0.2, -0.3],
    [0.1, 0.4]
])
B = np.array([[0.2, 0.1]])
V = np.array([
    [-0.3],
    [0.2]
])
C = np.array([[-0.3]])
e = 0
p = False
while True:
    e += 1
    z = np.dot(X, W) + B
    h = relu(z)
    u = np.dot(h, V) + C
    o = sigmoid(u)
    d = Y - o
    do = d * sigmoid_derivative(o)
    dh = do.dot(V.T) * relu_derivative(z)
    V += l * h.T.dot(do)
    C += l * do
    W += l * X.T.dot(dh)
    B += l * dh
    if not p:
        print("\n--- First Epoch ---")
        print("Output:", o.item())
        print("Error:", d.item())
        print("Updated W1:")
        for i in range(W.shape[0]):
            for j in range(W.shape[1]):
                print(f"  W{i+1}{j+1}: {W[i,j]}")
        print("Updated b1:")
        for j in range(B.shape[1]):
            print(f"  b1_{j+1}: {B[0,j]}")
        print("Updated W2:")
        for i in range(V.shape[0]):
            print(f"  W2_{i+1}: {V[i,0]}")
        print("Updated b2:")
        print(f"  b2: {C[0,0]}")
        p = True
    if abs(d.item()) < t:
        print("\n--- Last Epoch ---")
        print("Epoch:", e)
        print("Output:", o.item())
        print("Error:", d.item())
        print("Final W1:")
        for i in range(W.shape[0]):
            for j in range(W.shape[1]):
                print(f"  W{i+1}{j+1}: {W[i,j]}")
        print("Final b1:")
        for j in range(B.shape[1]):
            print(f"  b1_{j+1}: {B[0,j]}")
        print("Final W2:")
        for i in range(V.shape[0]):
            print(f"  W2_{i+1}: {V[i,0]}")
        print("Final b2:")
        print(f"  b2: {C[0,0]}")
        break



--- First Epoch ---
Output: 0.4452207648927852
Error: 0.5547792351072147
Updated W1:
  W11: 0.27163478029421056
  W12: 0.11891014647052629
  W21: -0.22836521970578944
  W22: 0.4189101464705263
  W31: 0.2
  W32: -0.3
  W41: 0.07163478029421058
  W42: 0.4189101464705263
Updated b1:
  b1_1: 0.1716347802942106
  b1_2: 0.11891014647052629
Updated W2:
  W2_1: -0.26217970705894744
  W2_2: 0.2945507323526314
Updated b2:
  b2: -0.2054492676473686

--- Last Epoch ---
Epoch: 29883
Output: 0.9990000045364771
Error: 0.000999995463522918
Final W1:
  W11: 0.19432310932229485
  W12: 0.7549097435247236
  W21: -0.30567689067770515
  W22: 1.0549097435247379
  W31: 0.2
  W32: -0.3
  W41: -0.00567689067770511
  W42: 1.0549097435247379
Final b1:
  b1_1: 0.09432310932229487
  b1_2: 0.7549097435247236
Final W2:
  W2_1: -0.21095166936500265
  W2_2: 1.7580425580882713
Final b2:
  b2: 0.5432982004359656
